<a href="https://colab.research.google.com/github/heena2248/Text_Mining/blob/main/TextMining3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Word preprocessing techniques
1. OHE (rarely used)
2. BOW (uses CountVectorizer)- doesnt capture the semantic meaning perfectly- uni grams
3. N-grams- include a range in CountVectorizer class- helps to capture semantic meanings better than bow- disadv: out of vocabulary not handled, leads to large no. of features
4. TF-IDF- tf(t,d) = count of t in d / number of words in d
idf(t) = log(N/ df(t))
df(t) = Document frequency of a term t
5. Custom features- number of alphabets in a word, or the average length of word, or anything else, as per the problem
6. Word Embeddings (using Word2Vec)

Word Embeddings- represents words as vector such that similar word vectors are close to each other. Handles semantic meaning, low dimensional vector and not sparse. Pretrained model using Gensim

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'Text':['Alex teaches NLP','Alex provides training', 'People write comments comments','Alex write comments'], 'Output' : [1, 1, 0, 1]})
df

Text  Output
0                Alex teaches NLP       1
1          Alex provides training       1
2  People write comments comments       0
3             Alex write comments       1

In [ ]:
# Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
countvect = CountVectorizer(binary=False)

In [ ]:
countvect1 = CountVectorizer(binary=True) # Binary BOW

In [ ]:
BagOfWord = countvect.fit_transform(df['Text']).toarray()
BagOfWord1= countvect1.fit_transform(df['Text']).toarray()



In [ ]:
print(countvect.vocabulary_)
BagOfWord

{'alex': 0, 'teaches': 5, 'nlp': 2, 'provides': 4, 'training': 6, 'people': 3, 'write': 7, 'comments': 1}


array([[1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 0],
       [0, 2, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 1]])

In [ ]:
print(countvect1.vocabulary_)
BagOfWord1

{'alex': 0, 'teaches': 5, 'nlp': 2, 'provides': 4, 'training': 6, 'people': 3, 'write': 7, 'comments': 1}


array([[1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 1]])

Advantages: Simple,
Diasadv: Sparsity, not able to handle OutOfVocabulary, Ordering

Next is *n-grams*

In [ ]:
countvect1 = CountVectorizer(binary=True, ngram_range=(1, 2)) # ngram_range=(2, 2) - bi-grams
BagOfWord1 = countvect1.fit_transform(df['Text']).toarray()
print(countvect1.vocabulary_)

{'alex': 0, 'teaches': 11, 'nlp': 6, 'alex teaches': 2, 'teaches nlp': 12, 'provides': 9, 'training': 13, 'alex provides': 1, 'provides training': 10, 'people': 7, 'write': 14, 'comments': 4, 'people write': 8, 'write comments': 15, 'comments comments': 5, 'alex write': 3}


In [ ]:
BagOfWord1

array([[1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]])

Adv: able to capture some semantic meaning,

Disadv: Large no. of dimension, Out Of Vocabulary not handled

Tf-Idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
BagOfWord2 = tfidf.fit_transform(df['Text']).toarray()
print(tfidf.vocabulary_)

{'alex': 0, 'teaches': 5, 'nlp': 2, 'provides': 4, 'training': 6, 'people': 3, 'write': 7, 'comments': 1}


In [ ]:
BagOfWord2

array([[0.41137791, 0.        , 0.64450299, 0.        , 0.        ,
        0.64450299, 0.        , 0.        ],
       [0.41137791, 0.        , 0.        , 0.        , 0.64450299,
        0.        , 0.64450299, 0.        ],
       [0.        , 0.7779822 , 0.        , 0.49338588, 0.        ,
        0.        , 0.        , 0.3889911 ],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.61366674]])

Disadv: Sparsity, OOV not handles, high dimension

Word2Vec

In [ ]:
!pip install gensim

In [ ]:
import gensim
import os

In [ ]:

from gensim.models import Word2Vec,KeyedVectors

In [ ]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=0a3c4b4ad6b3b73a5aa2af13361b52baaaeea3a12a108cec01d77506cab762c9
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built wget


In [ ]:
text="Once upon a time there lived a cap seller in a small village, whose name was Sunil. Sunil was a good hearted and hard working man who used to make and sell caps of different colors and designs and earn his living. His caps were famous all over the world and people from neighboring villages used to come to buy his beautiful caps . One morning when Sunil was going to sell his caps, his eyes fell on the movement in the trees. He saw that a group of mischievous monkeys were jumping in the branches of the tree. He gets scared seeing the herd of those monkeys. Frightened, Sunil continues his onward journey thinking little of the animals at play. As he grows inside the forest, the strong sunlight starts falling on him and he starts feeling tired. To avoid the heat, he thinks of taking rest under a big tree. He falls asleep with his big bag full of hats next to him. Little did Sunil know that the mischievous monkeys had been watching over him all the way. Attracted by the colorful caps, the monkeys decided to play a prank on Sunil. One by one all the monkeys came down from the trees and stole the caps from his bag. Waking up from a restful sleep, Sunil prepared to proceed on his journey. But when he bagged the caps, he was heartbroken because his bag was empty. The mischievous monkeys had stolen all his caps. To get back his caps, Sunil started looking here and there, hoping to find something about those mischievous monkeys. He saw monkeys on the top of the high branches of the tree. They were teasing Sunil wearing those caps and laughing at him. unil made a clever plan to get his caps. He decided to fool the monkeys, to get back their caps. Taking off his own cap, he took it in his hand and threw it on the ground. Surprisingly, the monkeys also started repeating his act and started throwing their caps. Sunil understood that the monkeys were imitating him, so he started repeating the same thing again. He started throwing his cap on the ground again and again and every time the monkeys also started throwing their caps. Soon a huge pile of colorful caps formed in front of him. There came a time when Sunil collected his caps one by one and put them back in his bag. The monkeys kept watching in astonishment, while Sunil heaved a sigh of relief. The monkeys also realized that they had been fooled, so they ran away, leaving Sunil to continue his journey. From that day onwards Sunil became ever alert and kept an eye on his caps. He learned a valuable lesson that cleverness and quick thinking can help him overcome any difficulty. No matter what challenge or obstacle came his way, he knew that he could deal with any difficult situation with cleverness and utility. And so Sunil, the one with the colorful caps, kept moving ahead with the caps in his bag. By telling his stories, he kept helping to bring light in the lives of people. His story of monkeys and caps became famous in all the villages, became a symbol of cleverness and quick thinking power. Moral of the story : Cleverness and quick thinking help in overcoming every challenge."

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopword = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
# Function
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopword:
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)
text=remove_stopwords(text)

In [ ]:
story= []
import nltk
nltk.download('punkt')
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
for sentence in sent_tokenize(text):
  story.append(simple_preprocess(sentence))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
len(story)

36

In [ ]:
story

[['once',
  'upon',
  'time',
  'lived',
  'cap',
  'seller',
  'small',
  'village',
  'whose',
  'name',
  'sunil'],
 ['sunil',
  'good',
  'hearted',
  'hard',
  'working',
  'man',
  'used',
  'make',
  'sell',
  'caps',
  'different',
  'colors',
  'designs',
  'earn',
  'living'],
 ['his',
  'caps',
  'famous',
  'world',
  'people',
  'neighboring',
  'villages',
  'used',
  'come',
  'buy',
  'beautiful',
  'caps'],
 ['one',
  'morning',
  'sunil',
  'going',
  'sell',
  'caps',
  'eyes',
  'fell',
  'movement',
  'trees'],
 ['he',
  'saw',
  'group',
  'mischievous',
  'monkeys',
  'jumping',
  'branches',
  'tree'],
 ['he', 'gets', 'scared', 'seeing', 'herd', 'monkeys'],
 ['frightened',
  'sunil',
  'continues',
  'onward',
  'journey',
  'thinking',
  'little',
  'animals',
  'play'],
 ['as',
  'grows',
  'inside',
  'forest',
  'strong',
  'sunlight',
  'starts',
  'falling',
  'starts',
  'feeling',
  'tired'],
 ['to', 'avoid', 'heat', 'thinks', 'taking', 'rest', 'big', 't

In [ ]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,vector_size=100,
    alpha=0.03,
    min_alpha=0.0007,
    workers=4
)

In [ ]:
model.build_vocab(story)

In [ ]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(229, 1645)

In [ ]:
model.wv.most_similar('cap')

[('help', 0.18699510395526886),
 ('sunil', 0.14916221797466278),
 ('cleverness', 0.11229696124792099),
 ('also', 0.10765847563743591),
 ('one', 0.09777916222810745),
 ('trees', 0.08932717144489288),
 ('there', 0.08725639432668686),
 ('play', 0.0856696292757988),
 ('caps', 0.08445555716753006),
 ('branches', 0.07375489175319672)]

In [ ]:
model.wv.doesnt_match(['cap','sunil','monkeys'])

'monkeys'

In [ ]:
model.wv.similarity('cap','sunil')

0.14916222

In [ ]:
model.wv.similarity('sunil','monkeys')

-0.024004687

In [ ]:
vec=model.wv['sunil']+model.wv['challenge']-model.wv['caps']
model.wv.most_similar([vec])

[('challenge', 0.5975469350814819),
 ('sunil', 0.5158876180648804),
 ('saw', 0.1954452097415924),
 ('taking', 0.13447947800159454),
 ('became', 0.12543652951717377),
 ('little', 0.11599132418632507),
 ('repeating', 0.11236748844385147),
 ('his', 0.11157982051372528),
 ('cleverness', 0.0640450045466423),
 ('to', 0.058847520500421524)]

In [ ]:
model.wv.get_normed_vectors()

array([[-0.00987546,  0.00501596,  0.09017026, ..., -0.1245733 ,
         0.01530652,  0.11283041],
       [-0.14867249,  0.06348618,  0.089473  , ..., -0.04117276,
        -0.1642138 ,  0.07784426],
       [ 0.00179074,  0.05454732, -0.11949326, ...,  0.00893478,
         0.1441985 , -0.12339681],
       ...,
       [-0.04905067,  0.0029799 ,  0.03649073, ...,  0.09876472,
         0.1242244 , -0.06920107],
       [ 0.01202631,  0.1116285 ,  0.10085485, ...,  0.12003142,
        -0.0583408 , -0.13346174],
       [-0.02093566, -0.04219269, -0.03224304, ...,  0.02384952,
        -0.15082307, -0.09175296]], dtype=float32)

In [ ]:

y=model.wv.index_to_key

In [ ]:
y

['caps',
 'monkeys',
 'sunil',
 'he',
 'started',
 'one',
 'bag',
 'thinking',
 'kept',
 'mischievous',
 'him',
 'cleverness',
 'the',
 'came',
 'throwing',
 'get',
 'also',
 'became',
 'quick',
 'time',
 'cap',
 'colorful',
 'journey',
 'tree',
 'back',
 'story',
 'ground',
 'there',
 'every',
 'repeating',
 'help',
 'challenge',
 'watching',
 'decided',
 'branches',
 'starts',
 'play',
 'little',
 'to',
 'way',
 'big',
 'taking',
 'people',
 'villages',
 'trees',
 'saw',
 'sell',
 'his',
 'famous',
 'used']

In [ ]:
from sklearn.decomposition import PCA
from matplotlib import pyplot
pca=PCA(n_components=3)

In [ ]:
X=pca.fit_transform(model.wv.get_normed_vectors())

In [ ]:
X.shape

(50, 3)

In [ ]:
import plotly.express as px
fig=px.scatter_3d(X[:10],x=0,y=1,z=2,color=y[:10])
fig.show()

In [ ]:
# download glove and unzip it in Notebook.
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove*.zip

--2024-08-29 01:32:40--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2024-08-29 01:32:40--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2024-08-29 01:32:40--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glov

In [ ]:
# code for Glove word embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

x = {'text', 'the', 'leader', 'prime',
     'natural', 'language'}

# create the dict.
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)

# number of unique words in dict.
print("Number of unique words in dictionary=",
      len(tokenizer.word_index))
print("Dictionary is = ", tokenizer.word_index)



# vocab: 'the': 1, mapping of words with
# integers in seq. 1,2,3..
# embedding: 1->dense vector
def embedding_for_vocab(filepath, word_index,
                        embedding_dim):
    vocab_size = len(word_index) + 1

    # Adding again 1 because of reserved 0 index
    embedding_matrix_vocab = np.zeros((vocab_size,
                                       embedding_dim))

    with open(filepath, encoding="utf8") as f:
        for line in f:
            word, *vector = line.split()
            if word in word_index:
                idx = word_index[word]
                embedding_matrix_vocab[idx] = np.array(
                    vector, dtype=np.float32)[:embedding_dim]

    return embedding_matrix_vocab


# matrix for vocab: word_index
embedding_dim = 50
embedding_matrix_vocab = embedding_for_vocab(
    'glove.6B.100d.txt', tokenizer.word_index,
  embedding_dim)

print("Dense vector for first word is => ",
      embedding_matrix_vocab[1])

Number of unique words in dictionary= 6
Dictionary is =  {'the': 1, 'leader': 2, 'text': 3, 'prime': 4, 'language': 5, 'natural': 6}
Dense vector for first word is =>  [-0.038194   -0.24487001  0.72812003 -0.39961001  0.083172    0.043953
 -0.39140999  0.3344     -0.57545     0.087459    0.28786999 -0.06731
  0.30906001 -0.26383999 -0.13231    -0.20757     0.33395001 -0.33848
 -0.31742999 -0.48335999  0.1464     -0.37303999  0.34577     0.052041
  0.44946    -0.46970999  0.02628    -0.54154998 -0.15518001 -0.14106999
 -0.039722    0.28277001  0.14393     0.23464    -0.31020999  0.086173
  0.20397     0.52623999  0.17163999 -0.082378   -0.71787    -0.41531
  0.20334999 -0.12763     0.41367     0.55186999  0.57907999 -0.33476999
 -0.36559001 -0.54856998]


In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('averaged_perceptron_tagger')
from nltk.tokenize import word_tokenize, sent_tokenize
stop_words = set(stopwords.words('english'))


txt = "Sukanya, Rajib and Naba are my good friends. " \
    "Sukanya is getting married next year. " \
    "Marriage is a big step in one’s life." \
    "It is both exciting and frightening. " \
    "But friendship is a sacred bond between people." \
    "It is a special kind of love between us. " \
    "Many of you must have tried searching for a friend "\
    "but never found the right one."

# sent_tokenize is one of instances of
# PunktSentenceTokenizer from the nltk.tokenize.punkt module

tokenized = sent_tokenize(txt)
for i in tokenized:

    # Word tokenizers is used to find the words
    # and punctuation in a string
    wordsList = nltk.word_tokenize(i)

    # removing stop words from wordList
    wordsList = [w for w in wordsList if not w in stop_words]

    #  Using a Tagger. Which is part-of-speech
    # tagger or POS-tagger.
    tagged = nltk.pos_tag(wordsList)

    print(tagged)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


[('Sukanya', 'NNP'), (',', ','), ('Rajib', 'NNP'), ('Naba', 'NNP'), ('good', 'JJ'), ('friends', 'NNS'), ('.', '.')]
[('Sukanya', 'NNP'), ('getting', 'VBG'), ('married', 'VBN'), ('next', 'JJ'), ('year', 'NN'), ('.', '.')]
[('Marriage', 'NN'), ('big', 'JJ'), ('step', 'NN'), ('one', 'CD'), ('’', 'NN'), ('life.It', 'NN'), ('exciting', 'VBG'), ('frightening', 'NN'), ('.', '.')]
[('But', 'CC'), ('friendship', 'NN'), ('sacred', 'VBD'), ('bond', 'NN'), ('people.It', 'NN'), ('special', 'JJ'), ('kind', 'NN'), ('love', 'VB'), ('us', 'PRP'), ('.', '.')]
[('Many', 'JJ'), ('must', 'MD'), ('tried', 'VB'), ('searching', 'VBG'), ('friend', 'NN'), ('never', 'RB'), ('found', 'VBD'), ('right', 'JJ'), ('one', 'CD'), ('.', '.')]
